# This file contains values from Cookiecutter

default_context:
  project_name: "snap-html"
  project_description: "a robust, modern and high performance Python library for generating image from a html string/html file/url build on top of `playwright`"
  organization: "codustry"
  license: "MIT"
  version: "0.1.0"
  github_name: "codustry"
  email: "hello@codustry.com"
